FROM node:22.13.0-alpine3.21 AS worker
RUN apk add --no-cache \
  git \
  bash

WORKDIR /home/logic
RUN git clone https://github.com/jackyzha0/quartz.git
WORKDIR /home/logic/quartz
RUN npm i

CMD ["npx", "quartz", "build", "--serve"]
